### ISSUE TITLE
Please discuss http://127.0.0.1:4000/blog/2022/04/25/nyuad here

### ISSUE THREAD

**Issue by jibri15** [vtomole/vtomole.github.io#31]
Please discuss http://127.0.0.1:4000/blog/2022/04/25/nyuad here

_Originally posted by @vtomole in https://github.com/vtomole/vtomole.github.io/discussions/29_

**Comment by vtomole** [comment]
Hey @jibri15, thanks for opening this.  I'm trying to encourage  discussions on Github Discussions instead of on the Issues
